-- Начальные данные каталога. Сгенерировано scripts/generate-seed.ts —
-- править этот файл руками бессмысленно, он перезаписывается.

begin;

-- ── курсы и уроки ──
insert into public.courses (slug, title, subtitle, category_id, cover, level, badges, author, description, published, sort_order) values (
  'remotion-video-kodom', 'Remotion: видео кодом', 'Ролик собирается из React, а не из дорожек в монтажке', 'ai',
  '{"from":"#F04A1E","to":"#2A0E0A","pattern":"grid","imageUrl":"https://kyutpzudsiifhdxysyff.supabase.co/storage/v1/object/public/covers/remotion-video-kodom.jpg"}'::jsonb, 'any', array['new', 'free'],
  'Цех', 'Видео как веб-страница: каждый кадр рисует код, а Remotion склеивает их в MP4. Разбираем, из чего состоит композиция, как считается время, почему анимация — это формула, и как поручить всю сборку Claude Code. К концу курса вы отрендерите свой первый ролик.', true, 0
) on conflict (slug) do update set
  title = excluded.title, subtitle = excluded.subtitle, category_id = excluded.category_id,
  cover = excluded.cover, level = excluded.level, badges = excluded.badges,
  author = excluded.author, description = excluded.description, sort_order = excluded.sort_order;

delete from public.lessons where course_id = (select id from public.courses where slug = 'remotion-video-kodom');
insert into public.lessons (course_id, position, title, duration_min, blocks)
select c.id, v.position, v.title, v.duration_min, v.blocks from public.courses c,
(values
  (1, 'Видео, которое собирает код', 5, '[{"type":"text","text":"Remotion делает видео из кода, а не из монтажа. Вы описываете ролик как обычную веб-страницу на React, а Remotion превращает её в готовый MP4. Никаких дорожек, ползунков и ручных ключевых точек."},{"type":"heading","text":"Флипбук, который рисует код"},{"type":"text","text":"Вспомните блокнот, где на каждой странице картинка чуть-чуть смещена: пролистали быстро — получился мультик. Remotion устроен так же, только каждую страницу рисует код, а листает их тридцать раз в секунду. Кадр видео — это снимок страницы в конкретный момент времени."},{"type":"image","cover":{"from":"#F04A1E","to":"#2A0E0A","pattern":"rings"},"caption":"Один и тот же компонент, тридцать разных моментов времени — секунда видео"},{"type":"heading","text":"Чем это отличается от монтажки"},{"type":"list","items":["В CapCut или Premiere вы двигаете элементы руками, и результат живёт внутри проекта редактора.","В Remotion вы записываете правило: «на пятнадцатом кадре карточка начинает появляться, к тридцатому она на месте». Правило срабатывает одинаково каждый раз.","Проект — это папка с кодом. Его можно хранить в Git, править текстом и собирать на сервере без человека."]},{"type":"callout","tone":"info","text":"Remotion не заменяет камеру. Он заменяет ручную работу над той частью ролика, которую и так рисует компьютер: текст, интерфейсы, графику, титры, инфографику."}]'::jsonb),
  (2, 'Зачем это, если есть монтажка', 6, '[{"type":"text","text":"Причина одна и называется она автоматизацией. Как только видео становится кодом, с ним можно делать всё то же, что с кодом: копировать, переиспользовать, менять в одном месте и собирать по кнопке."},{"type":"list","items":["Поправили текст в одной строке — он поменялся во всём ролике.","Однажды написали печатающийся по буквам заголовок — используете его в каждом следующем видео.","Подставили данные из таблицы — цены, имена, статистику — и они попали в кадр без ручного перенабора.","Отдали задачу нейросети: для неё код — родной язык, а монтажная программа — нет."]},{"type":"heading","text":"Сто роликов из одного шаблона"},{"type":"text","text":"Компонент принимает пропсы — те же данные, что и любой React-компонент. Значит один и тот же ролик можно отрендерить сто раз с разными подписями: поздравления с именами, отчёты по клиентам, карточки товаров."},{"type":"code","lang":"tsx","code":"type Props = { name: string; city: string }\n\nexport const Greeting: React.FC<Props> = ({ name, city }) => (\n  <AbsoluteFill>\n    <h1>{name}, привет из {city}</h1>\n  </AbsoluteFill>\n)"},{"type":"code","lang":"bash","code":"npx remotion render Greeting out/anna.mp4 --props=''{\"name\":\"Аня\",\"city\":\"Тбилиси\"}''"},{"type":"text","text":"Дальше это оборачивается в обычный цикл: список из ста строк — сто вызовов рендера. Работа, на которую в редакторе уходит неделя, занимает время, за которое остывает кофе."},{"type":"quote","text":"Если ролик нужно сделать один раз — берите монтажку. Если похожий ролик нужен снова и снова — берите код."}]'::jsonb),
  (3, 'Из чего собран кадр', 6, '[{"type":"text","text":"У проекта два слоя. Композиция — паспорт ролика: размер, частота кадров, длина. Компоненты — то, что в этом ролике происходит."},{"type":"heading","text":"Композиция"},{"type":"code","lang":"tsx","code":"import { Composition } from ''remotion''\nimport { Intro } from ''./Intro''\n\nexport const Root = () => (\n  <Composition\n    id=\"Intro\"\n    component={Intro}\n    durationInFrames={150}\n    fps={30}\n    width={1080}\n    height={1920}\n  />\n)"},{"type":"text","text":"Читается так: тридцать кадров в секунду, всего сто пятьдесят кадров — значит пять секунд. Кадр 1080 на 1920 — вертикаль под Reels, Shorts и Telegram."},{"type":"heading","text":"Компонент знает свой кадр"},{"type":"text","text":"Внутри компонента есть один хук, вокруг которого держится всё остальное: useCurrentFrame. Он отвечает на вопрос «какой сейчас кадр» — и от этого числа считается любое движение."},{"type":"code","lang":"tsx","code":"import { AbsoluteFill, useCurrentFrame, useVideoConfig } from ''remotion''\n\nexport const Intro = () => {\n  const frame = useCurrentFrame()\n  const { fps } = useVideoConfig()\n\n  // за первую секунду заголовок проявляется из нуля\n  const opacity = Math.min(frame / fps, 1)\n\n  return (\n    <AbsoluteFill style={{ justifyContent: ''center'', alignItems: ''center'' }}>\n      <h1 style={{ opacity }}>Цех</h1>\n    </AbsoluteFill>\n  )\n}"},{"type":"callout","tone":"warning","text":"CSS-анимации, setTimeout и любые «сам по себе идущий» эффекты в Remotion не работают. При рендере страница не проигрывается — у неё запрашивают отдельные кадры, иногда параллельно и не по порядку. Всё движение должно зависеть только от номера кадра."},{"type":"text","text":"Сцены собираются компонентом Sequence: он сдвигает время внутри себя. Обернули блок в Sequence с from={60} — и для этого блока отсчёт кадров начнётся на две секунды позже, а его собственный код об этом даже не узнает."}]'::jsonb),
  (4, 'Анимация — это формула', 7, '[{"type":"text","text":"В монтажке анимация — это две точки на таймлайне и кривая между ними, которую вы тянете мышкой. В Remotion это функция: на входе номер кадра, на выходе число — прозрачность, сдвиг, масштаб."},{"type":"heading","text":"interpolate: кадры в значения"},{"type":"code","lang":"tsx","code":"import { interpolate, useCurrentFrame } from ''remotion''\n\nconst frame = useCurrentFrame()\n\n// с 15-го по 30-й кадр прозрачность идёт от 0 к 1\nconst opacity = interpolate(frame, [15, 30], [0, 1], {\n  extrapolateLeft: ''clamp'',\n  extrapolateRight: ''clamp'',\n})"},{"type":"text","text":"Clamp здесь обязателен. Без него формула честно продолжит считать за границами диапазона: до пятнадцатого кадра прозрачность уйдёт в минус, после тридцатого — за единицу, и элемент начнёт вести себя странно."},{"type":"heading","text":"spring: движение как в жизни"},{"type":"text","text":"Линейное движение выглядит механическим — настоящие предметы разгоняются и тормозят. Функция spring имитирует пружину и делает это за вас."},{"type":"code","lang":"tsx","code":"import { spring, useCurrentFrame, useVideoConfig } from ''remotion''\n\nconst frame = useCurrentFrame()\nconst { fps } = useVideoConfig()\n\n// плавный выезд без отскока\nconst progress = spring({ frame, fps, config: { damping: 200 } })\nconst translateY = (1 - progress) * 80"},{"type":"list","items":["damping: 200 — спокойное появление без отскока, годится почти везде.","damping: 20, stiffness: 200 — резкое, «щелчком»: кнопки, счётчики, акценты.","damping: 8 — заметный отскок для игривых сцен. В деловом ролике будет лишним."]},{"type":"callout","tone":"success","text":"Написали такое появление один раз — вынесли в компонент Reveal и дальше просто оборачиваете в него всё, что должно выезжать. Ролики начинают выглядеть как одна серия, а не набор случайных эффектов."}]'::jsonb),
  (5, 'Звук задаёт длину ролика', 6, '[{"type":"text","text":"Озвучку не обязательно записывать голосом. Бесплатный edge-tts берёт текст и отдаёт готовый mp3 — этого достаточно для рекламного ролика или объяснялки."},{"type":"code","lang":"bash","code":"edge-tts --voice ru-RU-DmitryNeural \\\n  --text \"Claude Code собирает видео, пока вы пишете текст\" \\\n  --write-media public/voice.mp3"},{"type":"heading","text":"Подключить дорожку"},{"type":"code","lang":"tsx","code":"import { Audio } from ''@remotion/media''\nimport { staticFile } from ''remotion''\n\nexport const Scene = () => <Audio src={staticFile(''voice.mp3'')} />"},{"type":"heading","text":"Длину считает файл, а не глаз"},{"type":"text","text":"Главное правило со звуком: длина видео берётся из реальной длины аудио, а не ставится наугад. Формула простая — секунды озвучки умножить на частоту кадров."},{"type":"code","lang":"tsx","code":"import type { CalculateMetadataFunction } from ''remotion''\nimport { staticFile } from ''remotion''\nimport { getMediaMetadata } from ''./get-media-metadata''\n\nexport const calculateMetadata: CalculateMetadataFunction<Props> = async () => {\n  const { durationInSeconds } = await getMediaMetadata(staticFile(''voice.mp3''))\n\n  return { durationInFrames: Math.ceil(durationInSeconds * 30) }\n}"},{"type":"callout","tone":"warning","text":"Длина, вбитая руками, — источник половины проблем в готовых роликах: голос обрывается на полуслове или в конце висит секунда тишины. Пусть длину считает файл."}]'::jsonb),
  (6, 'Три скилла для Claude Code', 6, '[{"type":"text","text":"Скилл — это готовая инструкция, которая учит Claude Code делать конкретную часть работы. У Remotion таких инструкций три, и ставятся они одной командой."},{"type":"code","lang":"bash","code":"npx skills add remotion-dev/skills"},{"type":"list","ordered":true,"items":["/remotion-create — создаёт проект и композицию. Фундамент: размер кадра, частота, заготовка сцены.","/remotion-markup — строит дизайн и анимации: как всё выглядит и как двигается.","/remotion-render — превращает проект в MP4, который можно залить в Telegram, Reels или TikTok."]},{"type":"text","text":"Логика простая и всегда одна: создать → нарисовать → отрендерить. Вы описываете ролик словами — что за продукт, какой тон, сколько секунд, что должно быть в кадре, — а скиллы разводят эту задачу по трём этапам."},{"type":"quote","text":"Создай профессиональный Reel на 30 секунд про Remotion: тёмный фон, терминал в начале, текст печатается по буквам, в конце — призыв подписаться.","author":"Задача, которой хватает для первого ролика"},{"type":"callout","tone":"success","text":"Ролик, которым рекламируют эти скиллы, собран этими же скиллами. Ни монтажёра, ни таймлайна — только текст задачи, код и рендер."}]'::jsonb),
  (7, 'Первый ролик за вечер', 8, '[{"type":"text","text":"Порог входа ниже, чем кажется. Нужен компьютер с Node.js и желание один раз пройти путь целиком — от пустой папки до файла, который можно выложить."},{"type":"list","ordered":true,"items":["Поставить Node.js — движок, на котором всё работает.","Создать проект: npx create-video@latest — он задаст пару вопросов и соберёт заготовку.","Поставить скиллы: npx skills add remotion-dev/skills.","Открыть студию и смотреть, как ролик выглядит прямо в браузере.","Отрендерить MP4 и выложить."]},{"type":"code","lang":"bash","code":"npx create-video@latest\nnpx remotion studio"},{"type":"text","text":"Remotion Studio — это предпросмотр в Chrome: таймлайн, перемотка, мгновенное обновление после правки кода. Пока ролик не нравится, вы живёте здесь."},{"type":"heading","text":"Рендер"},{"type":"code","lang":"bash","code":"npx remotion render Intro out/video.mp4"},{"type":"text","text":"Первым аргументом идёт id композиции, вторым — куда положить файл. Всё, дальше это обычный MP4."},{"type":"heading","text":"Куда заходит, а куда нет"},{"type":"list","items":["Заходит: рекламные ролики, объяснялки, анимированная инфографика, титры, шаблонные видео с меняющимися данными.","Не заходит: съёмка живых людей, влоги, интервью и художественный монтаж «под настроение» — там сильнее обычная камера и рука монтажёра."]},{"type":"callout","tone":"info","text":"Проверьте себя перед рендером: длина считается по аудио, все анимации завязаны на useCurrentFrame, интерполяции обрезаны clamp, шрифты и картинки лежат в public. Четыре пункта закрывают почти все ошибки первых роликов."},{"type":"quote","text":"Раньше между идеей и готовым роликом стояли дизайнер, монтажёр и несколько вечеров. Теперь между ними стоит абзац текста."}]'::jsonb)
) as v(position, title, duration_min, blocks)
where c.slug = 'remotion-video-kodom';

commit;
